version: "3.6"
services:
  traefik:
    image: traefik:1.7
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        #delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role==manager]
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=loidoltdesign.com \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
      - source: acme.json
        target: /etc/traefik/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:traefik.loidoltdesign.com"

networks:
  web:
    external: true

configs:
  traefik.toml:
    file: ./traefik.toml