version: '3.6'

services:
  proxy:
    image: traefik:1.7.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: --web --docker --logLevel=INFO
    networks:
      - public
    # The traefik entryPoints
    ports:
      - "80:80"
      - "443:443"
    labels:
      # Make sure this domain points to your IP so that traefik can request a cert
      - "traefik.frontend.rule=Host:traefik.loidoltdesign.com"
      # Traefik will proxy to its own GUI
      - "traefik.port=8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik.toml:/traefik.toml
      - acme.json:/acme.json
networks:
  public:
    driver: overlay