version: "3.3"
services:
  traefik:
    image: traefik
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role==manager]
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=loidoltdesign.com \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:traefik.loidoltdesign.com"
      - "traefik.backend.loadbalancer.sticky=true"
      - "traefik.frontend.passHostHeader=true"

networks:
  web:
    external: true
