logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[web]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  #   [entryPoints.http.redirect]
  #       entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/downdraftdrones.com.crt"
      keyFile = "/etc/traefik/certs/downdraftdrones.key"

[acme]
  email = "loidolt@gmail.com"
  storage = "acme.json"
  entryPoint = "https"
  acmeLogging=true
  onDemand=true
  #OnHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "loidoltdesign.com"
watch = true
swarmMode = true
exposedbydefault = false