logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[web]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.auth.basic]
  users = ["user:HTTPSpassword"]
  #   [entryPoints.http.redirect]
  #       entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "loidolt@gmail.com"
  storage = "acme.json"
  entryPoint = "https"
  acmeLogging=true
  onDemand=true
  #OnHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
  domain = "loidoltdesign.com"
  watch = true
  swarmmode = true